import React, { useState } from 'react';
import { FileDown, Calendar, FileText, Filter, Sparkles, TrendingUp, BarChart3 } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const Reports = () => {
    const [reportType, setReportType] = useState('bookings');
    const [dateRange, setDateRange] = useState('this_month');
    const [isGenerating, setIsGenerating] = useState(false);

    const generatePDF = () => {
        setIsGenerating(true);
        const doc = new jsPDF();

        // Header with gradient effect
        doc.setFillColor(15, 23, 42);
        doc.rect(0, 0, 210, 40, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.text('Builty Transport Pakistan', 14, 25);
        doc.setFontSize(12);
        doc.text('Generated Report', 14, 33);
        doc.setFontSize(10);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 160, 25);

        let title = '';
        let head = [];
        let body = [];

        if (reportType === 'bookings') {
            title = 'Bookings Report - ' + dateRange.replace('_', ' ').toUpperCase();
            head = [['ID', 'Date', 'Transporter', 'From', 'To', 'Status']];
            body = [
                ['BK-1025', '2024-02-01', 'Raza Transport', 'Lahore', 'Karachi', 'In Transit'],
                ['BK-1024', '2024-02-01', 'City Logistics', 'Islamabad', 'Lahore', 'Pending'],
                ['BK-1023', '2024-01-31', 'Falcon Cargo', 'Karachi', 'Multan', 'Delivered'],
                ['BK-1022', '2024-01-30', 'Fast Movers', 'Peshawar', 'Lahore', 'Delivered'],
                ['BK-1021', '2024-01-28', 'Bilal Goods', 'Quetta', 'Karachi', 'In Transit'],
                ['BK-1020', '2024-01-27', 'Pak Goods', 'Faisalabad', 'Islamabad', 'Delivered'],
                ['BK-1015', '2024-01-22', 'City Logistics', 'Lahore', 'Gujranwala', 'Delivered'],
                ['BK-1012', '2024-01-18', 'Pak Goods', 'Faisalabad', 'Karachi', 'Delivered'],
            ];
        } else if (reportType === 'financial') {
            title = 'Financial Summary - ' + dateRange.replace('_', ' ').toUpperCase();
            head = [['Category', 'Description', 'Amount (PKR)', 'Type']];
            body = [
                ['Income', 'Freight Charges - BK-1025', '85,000', 'Credit'],
                ['Expense', 'Fuel Advance - V-9988', '25,000', 'Debit'],
                ['Income', 'Commission - BK-1022', '5,000', 'Credit'],
                ['Expense', 'Driver Salary - Ahmed', '40,000', 'Debit'],
                ['Income', 'Freight Charges - BK-1020', '120,000', 'Credit'],
            ];
        }

        doc.setTextColor(15, 23, 42);
        doc.setFontSize(16);
        doc.text(title, 14, 55);

        autoTable(doc, {
            startY: 65,
            head: head,
            body: body,
            theme: 'grid',
            headStyles: { fillColor: [59, 130, 246], textColor: 255 },
            styles: { fontSize: 10, cellPadding: 3 },
            alternateRowStyles: { fillColor: [241, 245, 249] }
        });

        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(100);
            doc.text(`Page ${i} of ${pageCount} - Generated by Builty Web App`, 14, 290);
        }

        doc.save(`builty_report_${reportType}_${Date.now()}.pdf`);
        setIsGenerating(false);
    };

    return (
        <div className="space-y-8 text-text-main">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div>
                    <h2 className="text-3xl font-bold gradient-text tracking-tight">Reports</h2>
                    <p className="text-slate-400 mt-1">Generate and download professional PDF reports</p>
                </div>
                <div className="hidden md:flex items-center space-x-2 px-4 py-2 rounded-full bg-gradient-to-r from-blue-500/10 to-violet-500/10 border border-white/10">
                    <Sparkles className="w-4 h-4 text-violet-400" />
                    <span className="text-sm text-slate-300">AI-Powered Reports</span>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                {/* Configuration Card */}
                <div className="lg:col-span-2 glass-card p-8 space-y-8">
                    <div className="flex items-center space-x-3">
                        <div className="p-3 rounded-xl bg-gradient-to-br from-blue-500/20 to-violet-500/20 border border-white/10">
                            <Filter className="w-6 h-6 text-blue-400" />
                        </div>
                        <h3 className="text-xl font-bold text-white">Report Configuration</h3>
                    </div>

                    <div className="space-y-6">
                        {/* Report Type Selection */}
                        <div>
                            <label className="block text-sm font-medium text-slate-400 mb-3">Select Report Type</label>
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                <button
                                    onClick={() => setReportType('bookings')}
                                    className={`group relative p-5 rounded-2xl border-2 transition-all duration-300 text-left overflow-hidden
                                        ${reportType === 'bookings'
                                            ? 'border-blue-500 bg-blue-500/10'
                                            : 'border-slate-700/50 bg-slate-800/30 hover:border-slate-600 hover:bg-slate-800/50'}
                                    `}
                                >
                                    {reportType === 'bookings' && (
                                        <div className="absolute inset-0 bg-gradient-to-br from-blue-500/10 to-transparent" />
                                    )}
                                    <div className="relative z-10 flex items-center space-x-4">
                                        <div className={`p-3 rounded-xl transition-colors ${reportType === 'bookings' ? 'bg-blue-500/20' : 'bg-slate-700/50 group-hover:bg-slate-700'}`}>
                                            <BarChart3 className={`w-6 h-6 ${reportType === 'bookings' ? 'text-blue-400' : 'text-slate-400 group-hover:text-slate-300'}`} />
                                        </div>
                                        <div>
                                            <span className={`font-semibold block ${reportType === 'bookings' ? 'text-white' : 'text-slate-300'}`}>Bookings / Operations</span>
                                            <span className="text-xs text-slate-500">All shipment data</span>
                                        </div>
                                    </div>
                                </button>

                                <button
                                    onClick={() => setReportType('financial')}
                                    className={`group relative p-5 rounded-2xl border-2 transition-all duration-300 text-left overflow-hidden
                                        ${reportType === 'financial'
                                            ? 'border-emerald-500 bg-emerald-500/10'
                                            : 'border-slate-700/50 bg-slate-800/30 hover:border-slate-600 hover:bg-slate-800/50'}
                                    `}
                                >
                                    {reportType === 'financial' && (
                                        <div className="absolute inset-0 bg-gradient-to-br from-emerald-500/10 to-transparent" />
                                    )}
                                    <div className="relative z-10 flex items-center space-x-4">
                                        <div className={`p-3 rounded-xl transition-colors ${reportType === 'financial' ? 'bg-emerald-500/20' : 'bg-slate-700/50 group-hover:bg-slate-700'}`}>
                                            <TrendingUp className={`w-6 h-6 ${reportType === 'financial' ? 'text-emerald-400' : 'text-slate-400 group-hover:text-slate-300'}`} />
                                        </div>
                                        <div>
                                            <span className={`font-semibold block ${reportType === 'financial' ? 'text-white' : 'text-slate-300'}`}>Financial Summary</span>
                                            <span className="text-xs text-slate-500">Income & expenses</span>
                                        </div>
                                    </div>
                                </button>
                            </div>
                        </div>

                        {/* Date Range Selection */}
                        <div>
                            <label className="block text-sm font-medium text-slate-400 mb-3">Date Range</label>
                            <select
                                value={dateRange}
                                onChange={(e) => setDateRange(e.target.value)}
                                className="w-full input-modern"
                            >
                                <option value="today">Today</option>
                                <option value="this_week">This Week</option>
                                <option value="this_month">This Month</option>
                                <option value="last_month">Last Month</option>
                                <option value="year_to_date">Year to Date (YTD)</option>
                            </select>
                        </div>

                        {/* Generate Button */}
                        <div className="pt-4">
                            <button
                                onClick={generatePDF}
                                disabled={isGenerating}
                                className="w-full py-4 bg-gradient-to-r from-blue-600 to-violet-600 hover:from-blue-500 hover:to-violet-500 active:scale-[0.98] text-white rounded-2xl font-bold shadow-lg shadow-blue-500/25 flex items-center justify-center space-x-3 transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed group"
                            >
                                {isGenerating ? (
                                    <div className="flex items-center space-x-3">
                                        <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                                        <span>Generating Report...</span>
                                    </div>
                                ) : (
                                    <>
                                        <FileDown className="w-5 h-5 group-hover:animate-bounce" />
                                        <span>Download PDF Report</span>
                                    </>
                                )}
                            </button>
                        </div>
                    </div>
                </div>

                {/* Preview Card */}
                <div className="relative glass-card p-8 flex flex-col justify-center items-center text-center overflow-hidden">
                    {/* Background Decoration */}
                    <div className="absolute -top-20 -right-20 w-40 h-40 bg-blue-500/10 rounded-full blur-3xl" />
                    <div className="absolute -bottom-10 -left-10 w-32 h-32 bg-violet-500/10 rounded-full blur-3xl" />

                    <div className="relative z-10 space-y-6">
                        <div className="w-24 h-24 mx-auto bg-gradient-to-br from-blue-500/20 to-violet-500/20 rounded-3xl flex items-center justify-center border border-white/10 float">
                            <FileText className="w-12 h-12 text-blue-400" />
                        </div>

                        <div>
                            <h3 className="text-2xl font-bold text-white mb-2">Report Preview</h3>
                            <div className="space-y-1 text-slate-400">
                                <p className="text-sm">
                                    Type: <span className="text-white font-medium">{reportType === 'bookings' ? 'Bookings' : 'Financial'}</span>
                                </p>
                                <p className="text-sm">
                                    Period: <span className="text-white font-medium">{dateRange.replace('_', ' ')}</span>
                                </p>
                            </div>
                        </div>

                        <div className="px-4 py-3 rounded-xl bg-slate-800/50 border border-slate-700/50">
                            <p className="text-xs text-slate-500 leading-relaxed">
                                Your PDF will include formatted tables, company branding, and all relevant data points.
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Quick Stats */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                {[
                    { label: 'Total Reports', value: '156', color: 'blue' },
                    { label: 'This Month', value: '23', color: 'violet' },
                    { label: 'Avg. Generation', value: '2.3s', color: 'emerald' },
                    { label: 'Downloads', value: '1.2K', color: 'orange' },
                ].map((stat, i) => (
                    <div key={i} className="stat-card text-center">
                        <p className="text-2xl font-bold text-white mb-1">{stat.value}</p>
                        <p className="text-xs text-slate-500">{stat.label}</p>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default Reports;
